export const ROUTE_MAP = {
  LOGIN: "/login",
  ACTIVATION: "/activation",
  SIGIL_DESIGNER: "/sigil-designer",
  IDS: "/ids",
  MANAGE: "/ids/manage",
  ONBOARDING: "/ids/onboarding",
  SET_UP: "/ids/manage/set-up",
  SPAWN_PROXY: "/ids/manage/settings/spawn-proxy",
  SETTINGS: "/ids/manage/settings",
  SPONSOR: "/ids/manage/settings/sponsor",
  OWNERSHIP: "/ids/manage/settings/ownership",
  MASTER_TICKET: "/ids/manage/settings/master-ticket",
  NETWORK_KEYS: "/ids/manage/settings/network-keys",
  HISTORY: "/ids/manage/history",
  SPAWN: "/ids/manage/settings/spawn",
  MANAGEMENT_KEY: "/ids/manage/settings/management-key",
};
