const ETHEREUM_NETWORK = {
  MAINNET: "mainnet",
  SEPOLIA: "sepolia",
  LOCAL: "local",
} as const;

const LOGIN_METHODS = {
  BLOCKNATIVE: Symbol("BLOCKNATIVE"),
  TICKET: Symbol("TICKET"),
  SEED: Symbol("SEED"),
};

const DEFAULT_HD_PATH = "m/44'/60'/0'/0/0";
const ETH_ZERO_ADDR = "0x0000000000000000000000000000000000000000";
const ETH_ZERO_ADDR_SHORT = "0x0";

const EIP1559_TRANSACTION_TYPE = 2;

// Chain IDs
// https://chainlist.org/?testnets=true
const ETHEREUM_MAINNET_CHAIN_ID = "0x1";
const ETHEREUM_LOCAL_CHAIN_ID = "0x539";
const ETHEREUM_SEPOLIA_CHAIN_ID = "0xaa36a7";

export {
  DEFAULT_HD_PATH,
  EIP1559_TRANSACTION_TYPE,
  ETH_ZERO_ADDR,
  ETH_ZERO_ADDR_SHORT,
  ETHEREUM_MAINNET_CHAIN_ID,
  ETHEREUM_LOCAL_CHAIN_ID,
  ETHEREUM_SEPOLIA_CHAIN_ID,
  ETHEREUM_NETWORK,
  LOGIN_METHODS,
};
